### ISSUE TITLE
Error on installing add-on

### ISSUE THREAD

**Issue by skleijkers** [corvy/ha-addons#2]
Hi,

I'm trying to install the GPSD to MQTT addon for Home Assistant, but I'm getting the following error on install:

Can't install sbarmen/amd64-addon-gpsd2mqtt:0.0.106a: 404 Client Error for http+docker://localhost/v1.42/images/create?tag=0.0.106a&fromImage=sbarmen%2Famd64-addon-gpsd2mqtt&platform=linux%2Famd64: Not Found ("manifest for sbarmen/amd64-addon-gpsd2mqtt:0.0.106a not found: manifest unknown: manifest unknown")

I think it tries to install a specific version (0.0.106a) and I don't find that one on the Docker hub.

Kind regards,
Stefan

**Comment by corvy** [comment]
Yeah that should not happen. Version 0.0.106 should be installed. I am just about to upgrade to 0.0.107, that should be out in a few hours. Hope that will fix the issue.

**Comment by corvy** [comment]
Hello Stefan, please try again now with the version 0.0.107 and see if that works for you. :)
