### ISSUE TITLE
Exeption in Home Assistant

### ISSUE THREAD

**Issue by elojn** [corvy/ha-addons#24]
I got this exeption in Homeassistant 

HA and GPSD to MQTT 2024.4.2
HA OS 12.1
Any idea?

Logger: homeassistant.components.mqtt.models
Quelle: components/mqtt/models.py:378
Integration: MQTT (Dokumentation, Probleme)
Erstmals aufgetreten: 17:21:10 (728 Vorkommnisse)
Zuletzt protokolliert: 19:34:27

Exception raised when updating state of device_tracker.gps_location, topic: 'gpsd2mqtt/fcbdedf5/attribute' with payload: b'{"class": "TPV", "device": "/dev/ttyACM0", "mode": 3, "time": "2024-04-18T17:33:43.000Z", "ept": 0.005, "altHAE": 891.4, "altMSL": 842.4, "epx": 9.206, "epy": 9.217, "epv": 32.2, "magvar": -0.2, "speed": 0.018, "climb": 0.2, "eps": 18.43, "epc": 64.4, "geoidSep": 49.0, "eph": 16.53, "sep": 31.35, "accuracy": "3D fix", "altitude": 842.4, "longitude": -2.8477295, "latitude": 38.936705333}'
Exception raised when updating state of device_tracker.gps_location, topic: 'gpsd2mqtt/fcbdedf5/attribute' with payload: b'{"class": "TPV", "device": "/dev/ttyACM0", "mode": 3, "time": "2024-04-18T17:33:54.000Z", "ept": 0.005, "altHAE": 891.2, "altMSL": 842.2, "epx": 9.206, "epy": 9.217, "epv": 32.2, "magvar": -0.2, "speed": 0.027, "climb": 0.0, "eps": 18.43, "epc": 64.4, "geoidSep": 49.0, "eph": 16.53, "sep": 31.35, "accuracy": "3D fix", "altitude": 842.2, "longitude": -2.847727667, "latitude": 38.936712667}'
Exception raised when updating state of device_tracker.gps_location, topic: 'gpsd2mqtt/fcbdedf5/attribute' with payload: b'{"class": "TPV", "device": "/dev/ttyACM0", "mode": 3, "time": "2024-04-18T17:34:05.000Z", "ept": 0.005, "altHAE": 890.1, "altMSL": 841.1, "epx": 9.096, "epy": 8.916, "epv": 32.2, "magvar": -0.2, "speed": 0.015, "climb": -0.2, "eps": 18.19, "epc": 64.4, "geoidSep": 49.0, "eph": 16.53, "sep": 31.35, "accuracy": "3D fix", "altitude": 841.1, "longitude": -2.847725333, "latitude": 38.936713333}'
Exception raised when updating state of device_tracker.gps_location, topic: 'gpsd2mqtt/fcbdedf5/attribute' with payload: b'{"class": "TPV", "device": "/dev/ttyACM0", "mode": 3, "time": "2024-04-18T17:34:16.000Z", "ept": 0.005, "altHAE": 890.1, "altMSL": 841.1, "epx": 9.096, "epy": 8.916, "epv": 28.06, "magvar": -0.2, "speed": 0.023, "climb": -0.1, "eps": 18.19, "epc": 56.12, "geoidSep": 49.0, "eph": 16.15, "sep": 28.12, "accuracy": "3D fix", "altitude": 841.1, "longitude": -2.847725, "latitude": 38.9367225}'
Exception raised when updating state of device_tracker.gps_location, topic: 'gpsd2mqtt/fcbdedf5/attribute' with payload: b'{"class": "TPV", "device": "/dev/ttyACM0", "mode": 3, "time": "2024-04-18T17:34:27.000Z", "ept": 0.005, "altHAE": 889.7, "altMSL": 840.7, "epx": 9.079, "epy": 8.927, "epv": 28.06, "magvar": -0.2, "speed": 0.027, "climb": 0.0, "eps": 18.16, "epc": 56.12, "geoidSep": 49.0, "eph": 16.15, "sep": 28.12, "accuracy": "3D fix", "altitude": 840.7, "longitude": -2.847721667, "latitude": 38.936730833}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 378, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1056, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 259, in state
    zone_state = zone.async_active_zone(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zone/__init__.py", line 139, in async_active_zone
    or not (zone_dist - (zone_radius := zone_attrs[ATTR_RADIUS]) < radius)
            ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'str'

**Comment by corvy** [comment]
I am failing to reproduce this problem. When does it happen? How do you reproduce it? Are you using any special automations or scripts that interact with the device_tracker? 

If possible could you run debug when you provoke the error?

**Comment by corvy** [comment]
Hello, please try the latest release and see if this problem has been fixed. 

Thank you!

**Comment by corvy** [comment]
@elojn any feedback on the new version?

**Comment by elojn** [comment]
Hi @corvy,

sorry, but I got same error:

Logger: homeassistant.components.mqtt.models
Quelle: components/mqtt/models.py:378
Integration: MQTT (Dokumentation, Probleme)
Erstmals aufgetreten: 29. April 2024 um 16:36:10 (25510 Vorkommnisse)
Zuletzt protokolliert: 22:32:44

Exception raised when updating state of device_tracker.gps_location, topic: 'gpsd2mqtt/fcbdedf5/attribute' with payload: b'{"class": "TPV", "device": "/dev/ttyACM0", "mode": 3, "time": "2024-05-02T20:32:00.000Z", "ept": 0.005, "altHAE": 57.9, "altMSL": 11.3, "epx": 8.577, "epy": 8.749, "epv": 30.82, "magvar": -1.3, "speed": 0.002, "climb": 0.0, "eps": 17.5, "epc": 61.64, "geoidSep": 46.6, "eph": 16.34, "sep": 30.21, "accuracy": "3D fix", "altitude": 11.3, "longitude": -6.396003333, "latitude": 36.761847833}'
Exception raised when updating state of device_tracker.gps_location, topic: 'gpsd2mqtt/fcbdedf5/attribute' with payload: b'{"class": "TPV", "device": "/dev/ttyACM0", "mode": 3, "time": "2024-05-02T20:32:11.000Z", "ept": 0.005, "altHAE": 57.9, "altMSL": 11.3, "epx": 8.612, "epy": 8.716, "epv": 30.82, "magvar": -1.3, "speed": 0.013, "climb": 0.1, "eps": 17.43, "epc": 61.64, "geoidSep": 46.6, "eph": 16.34, "sep": 30.21, "accuracy": "3D fix", "altitude": 11.3, "longitude": -6.396007333, "latitude": 36.761843833}'
Exception raised when updating state of device_tracker.gps_location, topic: 'gpsd2mqtt/fcbdedf5/attribute' with payload: b'{"class": "TPV", "device": "/dev/ttyACM0", "mode": 3, "time": "2024-05-02T20:32:22.000Z", "ept": 0.005, "altHAE": 58.2, "altMSL": 11.6, "epx": 8.612, "epy": 8.716, "epv": 29.44, "magvar": -1.3, "speed": 0.003, "climb": 0.2, "eps": 17.43, "epc": 60.26, "geoidSep": 46.6, "eph": 15.58, "sep": 28.88, "accuracy": "3D fix", "altitude": 11.6, "longitude": -6.396012333, "latitude": 36.761840167}'
Exception raised when updating state of device_tracker.gps_location, topic: 'gpsd2mqtt/fcbdedf5/attribute' with payload: b'{"class": "TPV", "device": "/dev/ttyACM0", "mode": 3, "time": "2024-05-02T20:32:33.000Z", "ept": 0.005, "altHAE": 59.1, "altMSL": 12.5, "epx": 8.62, "epy": 8.711, "epv": 30.82, "magvar": -1.3, "speed": 0.003, "climb": 0.1, "eps": 17.43, "epc": 61.64, "geoidSep": 46.6, "eph": 16.34, "sep": 30.21, "accuracy": "3D fix", "altitude": 12.5, "longitude": -6.396013833, "latitude": 36.761839}'
Exception raised when updating state of device_tracker.gps_location, topic: 'gpsd2mqtt/fcbdedf5/attribute' with payload: b'{"class": "TPV", "device": "/dev/ttyACM0", "mode": 3, "time": "2024-05-02T20:32:44.000Z", "ept": 0.005, "altHAE": 60.1, "altMSL": 13.5, "epx": 8.629, "epy": 8.74, "epv": 30.82, "magvar": -1.3, "speed": 0.005, "climb": 0.1, "eps": 17.48, "epc": 61.64, "geoidSep": 46.6, "eph": 16.34, "sep": 30.21, "accuracy": "3D fix", "altitude": 13.5, "longitude": -6.3960145, "latitude": 36.761838333}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 378, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1056, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 259, in state
    zone_state = zone.async_active_zone(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/zone/__init__.py", line 139, in async_active_zone
    or not (zone_dist - (zone_radius := zone_attrs[ATTR_RADIUS]) < radius)
            ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'float' and 'str'

**Comment by corvy** [comment]
Thank you! 

Not sure how to reproduce this problem. The error indicates that values for zone is not a number but rather a string. Do you have any special automations or configs around the device_tracker running? Something like calculations around distance to zone (proximity sensor perhaps?).

If you could explain your setup and what you do to provoke this error that would be helpful. Also if you could send me debugs from the addon if that is easy to do when the error happens.

If you go to Settings -> Integrations -> MQTT (https://HA_URL/config/devices/dashboard?historyBack=1&domain=mqtt) and click on "GPSD Service". Do you get two sensors? Both the device tracker (Location) and the Sky Data? Do they update on a regular interval? Or does the addon crash? 

Sorry to not be of any more help at this point but I struggle to understand what happens here.

**Comment by corvy** [comment]
Since I have not heard more from you I will consider this issue closed.
