### ISSUE TITLE
Location is fixed on "3d fix"

### ISSUE THREAD

**Issue by skleijkers** [corvy/ha-addons#4]
Hi,

Back again! :)

Almost everything works, but I have something weird, I also created a user and used the GPS location on it (I'll be using it in a Camper). But when I go to the entity it doesn't update the location to a location in a zone, see the picture:
<img width="584" alt="Scherm­afbeelding 2023-06-08 om 11 07 29" src="https://github.com/corvy/ha-addons/assets/67790366/e7151861-57a0-4330-9a8f-a5eb18c22c8c">

And I have a second thing: When I click on the map and want to zoom in/out it resets to the position of the gps in standard zoom. I think it updates to that default when the MQTT gets an update and that's every second... Would it be an option to introduce a timer for updating?

Stefan

**Comment by corvy** [comment]
Thanks for suggestions! 

Yes the 3D fix state is set by GPSD. 3D Fix means the "best possible" location fix. On location you could also get no fix and 2D fix. 

But that state could be publised to an attribute instead. Does not have to be in the state. I can change that to be part of the attributes list instead and leave state unchanged. 

Timer could be an option yes. I will look into that!

**Comment by corvy** [comment]
Just for info, still working on this. Hope to get a new version later today or tomorrow.

**Comment by corvy** [comment]
Quite a few new changes in the 2023.6.1 version. Try that out and see if that works better for you. Your requests are baked in this release, with the state not changed but GPS FIX but rather state from zone. Also the logging is improved and both logging and state publish frequency can be changed in the new optional options. Please let me know how it works for you. 

Thanks!

**Comment by corvy** [comment]
![Screenshot_20230610_195257_Home Assistant](https://github.com/corvy/ha-addons/assets/138292/95d88955-37ce-486f-8df5-cc6ae287025f)

The new version works well for me at least. 👍

**Comment by skleijkers** [comment]
Ah thx! I'll give it a try!

**Comment by skleijkers** [comment]
Works like a charm! Many thanks!

**Comment by corvy** [comment]
Love it! Thanks for reporting back!
